# Generated by Django 4.2.2 on 2023-09-26 23:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Client', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(null=True)),
                ('date_updated', models.DateTimeField(null=True)),
                ('status', models.CharField(choices=[('NC', 'Not created'), ('OG', 'On going'), ('DO', 'Done')], default='NC', max_length=2, null=True)),
                ('amount', models.FloatField(null=True)),
                ('payment_due', models.DateTimeField(null=True)),
                ('client', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Client.client')),
            ],
        ),
    ]
