# Generated by Django 4.2.2 on 2023-09-26 23:48

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Contract', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(null=True)),
                ('date_updated', models.DateTimeField(null=True)),
                ('status', models.BooleanField(default=True, null=True)),
                ('attendees', models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(200)])),
                ('event_start', models.DateTimeField(null=True)),
                ('event_end', models.DateTimeField(null=True)),
                ('location', models.CharField(max_length=250, null=True)),
                ('notes', models.TextField(null=True)),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Contract.contract')),
            ],
        ),
    ]
