# Generated by Django 4.2.2 on 2023-10-05 04:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Contract', '0002_initial'),
        ('Event', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='contract',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Contract.contract'),
        ),
    ]
