# Generated by Django 4.2.2 on 2023-09-27 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Staff', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='group',
            field=models.CharField(choices=[('SA', 'Sales'), ('SU', 'Support'), ('MA', 'Management')], max_length=2),
        ),
    ]
